#------------------------------------------------------------------------------
#
# 本番用
#
# Usage
#
# $ expose COMPOSE_FILE=./docker-compose.yml
# $ docker-compose build
# $ docker-compose up -d
#
#------------------------------------------------------------------------------
version: "3.2"
services:

  #
  # Frontend Webserver container
  #
  web-front:
    image: hidyon/wenow-front
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: wenow-front
    ports:
      - 80:80
    networks:
      - wenow-webnet
    depends_on:
      - wenow-mongo
      - wenow-back
    #links:
    #- wenow-back
    restart: always

  #
  # Backend Server container
  #
  wenow-back:
    image: hidyon/wenow-back
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: wenow-back
    ports:
      - 3000:3000
    networks:
      - wenow-webnet
    depends_on:
      - wenow-mongo
    #links:
    #- wenow-mongo
    restart: always

  #
  # MongoDB container
  #
  # ルート権限をもつユーザー・パスワードを登録 
  # ($MONGO_INITDB_ROOT_USERNAME, $MONGO_INITDB_ROOT_PASSWORD)
  # DBを作成　(DB名は${MONGO_INITDB_DATABASE)
  #
  # docker-compose up -d　の実行時に
  # ./mongo/docker-entrypoint-initdb.d/init.js を実行
  # データベースの一般ユーザー登録、初期データ搭載 
  #
  wenow-mongo:
    image: mongo:4.2.6-bionic
    container_name: wenow-mongo
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - 27017:27017
    networks:
      - wenow-webnet
    restart: always

  #
  # MongoDB GUI Client container
  #
  wenow-mongo-express:
    image: mongo-express:0.54.0
    container_name: wenow-mongo-express
    ports:
      - 8081:8081
    networks:
      - wenow-webnet
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: wenow-mongo
      ME_CONFIG_BASICAUTH_UERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    depends_on:
      - wenow-mongo
    #links:
    #- wenow-mongo
    restart: always
  
networks:
  wenow-webnet:

